(defun on-clojure-mode ()
  (require 'paredit)
  (paredit-mode t)
  (when (package-installed-p 'yasnippet)
    (yas/minor-mode 1))
  (when (package-installed-p 'clj-refactor)
    (clj-refactor-mode 1)
    (cljr-add-keybindings-with-prefix "C-c r")))

(add-hook 'clojure-mode-hook 'on-clojure-mode)

(defvar lein-try-history nil)
(defun lein-try (lib-name)
  (interactive (list (read-string "What are we going to try today?: " nil 'lein-try-history)))
  (switch-to-buffer (concat "*lein-try-" lib-name "*"))
  (inferior-lisp (concat "lein try " lib-name)))
