(defun on-clojure-mode ()
  (require 'paredit)
  (paredit-mode t)
  (when (package-installed-p 'yasnippet)
    (yas/minor-mode 1))
  (when (package-installed-p 'clj-refactor)
    (clj-refactor-mode 1)
    (cljr-add-keybindings-with-prefix "C-c r")))

(add-hook 'clojure-mode-hook 'on-clojure-mode)
